### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gmalmeida** [AstroTech/atlassian-python-api#4]
Thanks @MattAgile  for this nice start-up, I am wondering how can I send attachment files to a confluence page. I guess this is not included in your API. Any plans to do so? Thanks!

**Comment by MattAgile** [comment]
Hi,
Unfortunately this feature has not been implemented yet. Currently I have very little time to do so, however you will be most welcome to contribute. I am always looking forward for new Pull Requests :)

**Comment by gmalmeida** [comment]
Sure Matt, I try to come up with something.
